const VERSION='5.1-web',STORE='studio24-live-v1';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],fmt=n=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n||0),nf=n=>new Intl.NumberFormat('fr-FR',{maximumFractionDigits:1}).format(n||0),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),pick=a=>a[Math.floor(Math.random()*a.length)];
const pages=['dashboard','schedule','programs','production','catalog','audience','competition','staff','talentmarket','seasons','advertising','news','digital','life','network','sports','finance','studios','strategy'];
const labels={dashboard:'Tableau de bord',schedule:'Grille TV',programs:'Programmes',production:'Production',catalog:'Achats & catalogue',audience:'Audiences',competition:'Concurrence',staff:'Personnel',talentmarket:'Mercato TV',seasons:'Saisons & formats',advertising:'Publicité',news:'Rédaction',digital:'Streaming & replay',life:'Vie de chaîne',network:'Groupe média',sports:'Droits sportifs',finance:'Finances',studios:'Studios',strategy:'Stratégie'};
const basePrograms=[['Bonjour Région','Info',7200,58,46,'25-49'],['Le 12/30','Info',5800,64,52,'35-59'],['Nos Routes','Doc',4600,61,43,'50+'],['Le Grand Quiz','Divertissement',10800,65,59,'Famille'],['Nova Soir','Info',13200,69,63,'35-59'],['En Direct','Talk',18800,66,55,'25-49'],['District 19','Fiction',15400,71,64,'15-34'],['Planète Sauvage','Doc',8300,74,57,'Famille'],['Terrain 24','Sport',12500,67,58,'25-49'],['Ciné Club','Cinéma',14500,68,51,'35-59']];
const baseStaff=[['Claire Dumas','Présentatrice / JT',75,72,5200],['Léo Martin','Journaliste',69,52,3900],['Emma Caron','Animatrice',73,68,4800],['Nicolas Rey','Consultant sport',68,61,4100],['Maya Chen','Directrice programmes',81,28,5600],['Hugo Vidal','Directeur commercial',70,24,4500],['Sarah Lopes','Réalisatrice',72,31,4300],['Tom Besson','Numérique / réseaux',64,36,3200],['Inès Garnier','Reporter',67,45,3600],['Romain Petit','Technicien régie',71,12,3400]];
function fresh(){return{version:VERSION,channel:'Nova 24',city:'Brive-la-Gaillarde',focus:'generaliste',cash:1050000,share:4,audience:340000,reputation:42,day:0,xp:18,lastProfit:0,history:[3.5,3.7,3.8,4],programs:basePrograms.map((p,i)=>({id:i+1,name:p[0],type:p[1],cost:p[2],quality:p[3],popularity:p[4],target:p[5],episodes:12-Math.min(i,8),status:'À l’antenne'})),schedule:['06:30','08:30','10:00','12:30','13:10','15:00','17:30','18:30','20:00','20:50','21:45','23:00'].map((t,i)=>({time:t,programId:[1,3,8,2,7,3,4,6,5,7,8,10][i]})),staff:baseStaff.map((x,i)=>({id:i+1,name:x[0],role:x[1],skill:x[2],popularity:x[3],salary:x[4],morale:78,loyalty:75,contract:18+i})),competitors:[{name:'Hexa 1',share:18.4,strength:84},{name:'Pulse TV',share:9.7,strength:72},{name:'France Régions',share:7.8,strength:69},{name:'Arena+',share:5.9,strength:66}],advertisers:[{name:'AutoNova',value:13200,min:3.5,active:true},{name:'HexaTel',value:9800,min:3.2,active:true},{name:'Maison & Vous',value:8700,min:3,active:true},{name:'FreshBox',value:11800,min:4.1,active:false}],rights:[{name:'Basket régional',cost:62000,potential:68,owned:false},{name:'Rugby — résumés',cost:94000,potential:73,owned:false},{name:'Handball — affiche régionale',cost:48000,potential:64,owned:false},{name:'Coupe nationale — 1 match',cost:185000,potential:88,owned:false}],productions:[],studios:[{name:'Plateau A',level:1,quality:64,capacity:120}],digital:{followers:68000,replay:22,streaming:false,subs:0},network:{channels:1,synergy:24},news:{credibility:61,budget:24000},events:[],strategy:'Développer une chaîne généraliste rentable',finance:[]}}
function load(){try{return JSON.parse(localStorage.getItem(STORE))}catch(e){return null}}let state=load(),page='dashboard';
function save(){if(state)localStorage.setItem(STORE,JSON.stringify(state))}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function modal(html){$('#modalBody').innerHTML=html;$('#modal').classList.remove('hidden')}function closeModal(){$('#modal').classList.add('hidden')}
function showTitle(){$('#titleScreen').classList.remove('hidden');$('#setup').classList.add('hidden');$('#game').classList.add('hidden');$('#titleContinue').classList.toggle('is-empty',!state);$('#titleContinue small').textContent=state?`${state.channel} · ${nf(state.share)} % PDM · ${fmt(state.cash)}`:'Aucune partie sauvegardée'}
function enterGame(){if(!state)return toast('Aucune partie sauvegardée');$('#titleScreen').classList.add('hidden');$('#setup').classList.add('hidden');$('#game').classList.remove('hidden');render()}
function startNew(){state=fresh();state.channel=$('#channelName').value.trim()||'Nova 24';state.city=$('#channelCity').value.trim()||'Brive-la-Gaillarde';state.focus=$('#channelFocus').value;const d=$('#difficulty').value;state.cash=d==='easy'?1450000:d==='hard'?720000:1050000;save();enterGame()}
function kpi(title,value,sub,cls=''){return `<div class="kpi ${cls}"><span>${title}</span><b>${value}</b><small>${sub}</small></div>`}
function card(title,body,actions=''){return `<article class="card"><div class="card-head"><h3>${title}</h3>${actions}</div>${body}</article>`}
function bar(v,max=100){return `<div class="meter"><i style="width:${clamp(v/max*100,2,100)}%"></i></div>`}
function hero(){return `<div class="premium-hq"><div class="hq-copy"><span class="tag">SIÈGE & ANTENNE</span><h2>${state.channel}</h2><p>${state.city} · ${state.staff.length} collaborateurs · ${state.studios.length} studio</p></div><div class="live-pill">● DIRECT</div></div>`}
function dashboard(){const top=[...state.programs].sort((a,b)=>b.popularity-a.popularity)[0];return `<div class="page-title"><div><span class="eyebrow">CENTRE DE COMMANDEMENT</span><h1>${state.channel}</h1><p>${state.strategy}</p></div><button class="primary" data-act="day">Diffuser la journée ▶</button></div><div class="kpis">${kpi('Audience',(state.audience/1e6).toFixed(2)+' M','Téléspectateurs')}${kpi('Part de marché',nf(state.share)+' %','National')}${kpi('Trésorerie',fmt(state.cash),'Disponible')}${kpi('Réputation',Math.round(state.reputation)+'/100','Image de marque')}</div>${hero()}<div class="grid two">${card('Ce soir sur '+state.channel,`<div class="showcase"><div class="poster">${top.name}</div><div><span class="tag">PROGRAMME PHARE</span><h2>${top.name}</h2><p>${top.type} · cible ${top.target}</p>${bar(top.popularity)}<small>Popularité ${Math.round(top.popularity)}/100 · Qualité ${Math.round(top.quality)}/100</small></div></div>`)}${card('Priorités Ariane',`<div class="advice"><b>${advice()[0]}</b><p>${advice()[1]}</p></div><button class="soft" data-act="ariane">Demander à Ariane</button>`)}</div><div class="module-grid">${pages.filter(x=>!['dashboard'].includes(x)).slice(0,8).map(x=>`<button class="module" data-page="${x}"><span>${iconFor(x)}</span><b>${labels[x]}</b><small>${descFor(x)}</small></button>`).join('')}</div>`}
function iconFor(x){return({schedule:'▤',programs:'▶',production:'🎬',catalog:'▣',audience:'⌁',competition:'⚔',staff:'♙',talentmarket:'✦',seasons:'◷',advertising:'◎',news:'●',digital:'⌁',life:'⚡',network:'⬡',sports:'★',finance:'€',studios:'▦',strategy:'◆'})[x]||'•'}function descFor(x){return({schedule:'Construis ta grille',programs:'Pilote tes émissions',production:'Crée tes contenus',catalog:'Achète films et formats',audience:'Comprends ton public',competition:'Surveille les rivaux',staff:'Gère ton équipe',talentmarket:'Recrute des vedettes'})[x]||'Gérer ce pôle'}
