function schedule(){return title('Grille TV','Chaque case influence l’audience, les recettes pub et l’usure des programmes')+card('Journée de diffusion',`<div class="schedule">${state.schedule.map((s,i)=>{const p=state.programs.find(x=>x.id==s.programId);return `<div class="slot"><b>${s.time}</b><div><strong>${p?.name||'Libre'}</strong><small>${p?.type||''} · coût ${fmt(p?.cost)}</small></div><button data-act="slot" data-i="${i}">Modifier</button></div>`}).join('')}</div>`)}
function programs(){return title('Programmes','Qualité, popularité, coût et saisons')+`<div class="grid three">${state.programs.map(p=>card(p.name,`<span class="tag">${p.type}</span><p>Cible ${p.target}</p><b>Popularité ${Math.round(p.popularity)}</b>${bar(p.popularity)}<small>Qualité ${p.quality} · ${p.episodes} épisodes restants · ${fmt(p.cost)}/diffusion</small>`,`<button data-act="boost" data-id="${p.id}">Promouvoir</button>`)).join('')}</div>`}
function production(){return title('Production','Développe des contenus originaux')+`<button class="primary" data-act="newprod">+ Nouvelle production</button><div class="grid two mt">${state.productions.length?state.productions.map(p=>card(p.name,`<p>${p.type}</p>${bar(p.progress)}<small>${p.progress}% · budget ${fmt(p.budget)}</small>`)).join(''):card('Aucune production en cours','<p>Lance une fiction, un jeu, un magazine ou un documentaire original.</p>')}</div>`}
function catalog(){const offers=[['Nuits de verre','Série premium',85000],['Planète Extrême','Documentaire',42000],['Rires en famille','Divertissement',56000],['Le Dernier Voyage','Film',68000]];return title('Achats & catalogue','Achète des droits de diffusion')+`<div class="grid two">${offers.map((o,i)=>card(o[0],`<span class="tag">${o[1]}</span><p>Droits 12 mois · 6 passages</p><b>${fmt(o[2])}</b>`,`<button data-act="buycat" data-name="${o[0]}" data-cost="${o[2]}">Acheter</button>`)).join('')}</div>`}
function audience(){return title('Audiences','Lis les tendances et les cibles')+`<div class="kpis">${kpi('15–34 ans',nf(state.share*.92)+' %','↗ cible jeune')}${kpi('25–49 ans',nf(state.share*1.08)+' %','Cœur commercial')}${kpi('50+',nf(state.share*.88)+' %','Public fidèle')}</div>${card('Historique PDM',`<div class="chart">${state.history.slice(-12).map(v=>`<i style="height:${Math.max(10,v*8)}px" title="${v}%"></i>`).join('')}</div><small>12 dernières journées disponibles</small>`)}`}
function competition(){return title('Concurrence','Les chaînes rivales évoluent avec toi')+`<div class="grid two">${state.competitors.map(c=>card(c.name,`<b>${nf(c.share)} % PDM</b>${bar(c.share,20)}<small>Puissance ${c.strength}/100</small>`)).join('')}</div>`}
function staff(){return title('Personnel','Contrats, compétences, moral et fidélité')+`<div class="grid three">${state.staff.map(s=>card(s.name,`<span class="tag">${s.role}</span><p>Compétence ${s.skill} · Popularité ${s.popularity}</p>${bar(s.morale)}<small>Moral ${s.morale} · contrat ${s.contract} mois · ${fmt(s.salary)}/mois</small>`,`<button data-act="raise" data-id="${s.id}">Prime</button>`)).join('')}</div>`}
function talentmarket(){const m=[['Jade Morel','Animatrice',79,6500],['Samir Lenoir','Journaliste',82,7200],['Lina Costa','Comédienne',76,5900],['Marc Vidal','Consultant sport',74,5100]];return title('Mercato TV','Débauche les talents avant tes rivaux')+`<div class="grid two">${m.map((x,i)=>card(x[0],`<span class="tag">${x[1]}</span><p>Note ${x[2]}/100</p><b>${fmt(x[3])}/mois</b>`,`<button data-act="hire" data-name="${x[0]}" data-role="${x[1]}" data-salary="${x[3]}" data-skill="${x[2]}">Recruter</button>`)).join('')}</div>`}
function seasons(){return title('Saisons & formats','Renouvelle, arrête ou relance tes émissions')+`<div class="grid three">${state.programs.map(p=>card(p.name,`<p>${p.episodes} épisodes restants</p>${bar(p.popularity)}<small>Popularité ${Math.round(p.popularity)}</small>`,`<button data-act="renew" data-id="${p.id}">Renouveler</button>`)).join('')}</div>`}
function advertising(){return title('Publicité','Transforme l’audience en revenus')+`<div class="grid two">${state.advertisers.map((a,i)=>card(a.name,`<p>Seuil ${a.min}% PDM</p><b>${fmt(a.value)}/jour</b><small>${a.active?'Contrat actif':'Disponible'}</small>`,`<button data-act="ad" data-i="${i}">${a.active?'Résilier':'Signer'}</button>`)).join('')}</div>`}
function news(){return title('Rédaction','Crédibilité, rapidité et choix éditoriaux')+`<div class="kpis">${kpi('Crédibilité',Math.round(state.news.credibility)+'/100','Confiance')}${kpi('Budget',fmt(state.news.budget),'Journalier')}</div>${card('Conférence de rédaction','<p>Choisis le sujet fort du prochain JT.</p><div class="choice-row"><button data-act="story" data-v="Scoop local">Scoop local</button><button data-act="story" data-v="Économie">Économie</button><button data-act="story" data-v="Sport">Sport</button></div>')}`}
function digital(){return title('Streaming & replay','Construis une seconde économie')+`<div class="kpis">${kpi('Abonnés sociaux',state.digital.followers.toLocaleString('fr-FR'),'Communauté')}${kpi('Replay',state.digital.replay+' %','Part de visionnage')}${kpi('Premium',state.digital.subs.toLocaleString('fr-FR'),'Abonnés payants')}</div>${card('Studio 24 Play',state.digital.streaming?'<p>Plateforme active. Les abonnements progressent avec la qualité du catalogue.</p>':'<p>Lance ta plateforme payante et crée un revenu récurrent.</p>',`<button data-act="stream">${state.digital.streaming?'Investir 35 000 €':'Lancer 180 000 €'}</button>`)}`}
function life(){return title('Vie de chaîne','Crises, buzz et décisions humaines')+card('Événements récents',state.events.length?`<div class="feed">${state.events.slice(0,8).map(e=>`<div><b>${e.title}</b><small>${e.text}</small></div>`).join('')}</div>`:'<p>Aucun incident majeur pour le moment.</p>')}
function network(){return title('Groupe média','Développe plusieurs marques et mutualise les coûts')+`<div class="kpis">${kpi('Chaînes',state.network.channels,'Dans le groupe')}${kpi('Synergie',state.network.synergy+'/100','Mutualisation')}</div>${card('Expansion',`<p>Créer une chaîne secondaire coûte 280 000 €. Elle apportera de nouvelles audiences mais aussi des charges.</p>`,`<button data-act="channel">Lancer une chaîne</button>`)}`}
function sports(){return title('Droits sportifs','Les événements peuvent bouleverser une soirée')+`<div class="grid two">${state.rights.map((r,i)=>card(r.name,`<p>Potentiel ${r.potential}/100</p><b>${fmt(r.cost)}</b><small>${r.owned?'Droits acquis':'Disponible'}</small>`,`<button data-act="rights" data-i="${i}" ${r.owned?'disabled':''}>${r.owned?'Acquis':'Acheter'}</button>`)).join('')}</div>`}
function finance(){const sal=state.staff.reduce((a,s)=>a+s.salary,0);return title('Finances','Contrôle les coûts avant qu’ils contrôlent ta chaîne')+`<div class="kpis">${kpi('Trésorerie',fmt(state.cash),'Disponible')}${kpi('Dernier résultat',fmt(state.lastProfit),'Journée')}${kpi('Masse salariale',fmt(sal),'/mois')}</div>${card('Historique résultat',`<div class="feed">${state.finance.slice(-10).reverse().map(x=>`<div><b>Jour ${x.day}</b><small>${fmt(x.profit)}</small></div>`).join('')||'<p>Diffuse une journée pour obtenir les premiers comptes.</p>'}`)}`}
function studios(){return title('Studios','Capacité, qualité et infrastructure')+`<div class="grid two">${state.studios.map((s,i)=>card(s.name,`<p>Niveau ${s.level} · ${s.capacity} places</p>${bar(s.quality)}<small>Qualité technique ${s.quality}/100</small>`,`<button data-act="studio" data-i="${i}">Améliorer ${fmt(95000*s.level)}</button>`)).join('')}</div>`}
function strategy(){return title('Stratégie','Donne un cap à Ariane et à la chaîne')+card('Objectif actuel',`<h2>${state.strategy}</h2><p>Ta stratégie influence la façon dont tu interprètes les résultats.</p><div class="choice-row"><button data-act="strategy" data-v="Devenir leader des 15–34 ans">Jeunes</button><button data-act="strategy" data-v="Construire la chaîne familiale n°1">Famille</button><button data-act="strategy" data-v="Dominer l’information et la crédibilité">Info</button><button data-act="strategy" data-v="Croître sans mettre la trésorerie en danger">Rentabilité</button></div>`) }
